GET http://localhost:3001/api/notes

###
GET http://localhost:3001

###
GET http://localhost:3001/api/notes/1

###
POST http://localhost:3001/api/notes
content-type: application/json  

{
    "name": "sample",
    "content": "example w/ content header"
}

###
POST http://localhost:3001/api/notes
content-type: application/json  

{
    "content": "GET and POST are the most important methods of HTTP protocol"
}

###
PUT http://localhost:3001/api/notes/6035ff52f52d3b563cf9cc6e
Content-Type: application/json

{
    "content" : "esto es una nota actualizada",
    "important": true
}

###
POST   http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Lucas",
    "name": "Superuser",
    "notes": [],
    "password": "supersecret"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikx1Y2FzIiwiaWQiOiI2MDU2N2Y2YzFjOWRhZjRhZDczZjg3NDMiLCJpYXQiOjE2MTY0NjIwNTB9.ASQP-j4vRdOxqtWnfdSw0JrEFGjLc5uW0s3Fobz-Nzs

{
    "content":"User id of the note creator es at the start sent along the request",
    "important": true,
    "userId": "60567049436f9741583c5c92"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "Lucas",
    "password": "supersecret"
}

###
GET http://localhost:3001/api/users